### ISSUE TITLE
G⁶

### ISSUE THREAD

**Issue by trosadero** [skylar69-wtf/cchecker.github.io#2]

**Comment by BaliTheBoi** [comment]
how it check card is alive or declined without charging any money from card.

**Comment by skylar69-wtf** [comment]
> how it check card is alive or declined without charging any money from card.

auth thrgh free trial subscription

**Comment by BaliTheBoi** [comment]
okay. i will contact you on telegram.

**Comment by kkk200492** [comment]
Ok bro give me your username on tg plz
